//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelryBiz.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryConfiguration
    {
        public int ConfigurationId { get; set; }
        public int CategoryId { get; set; }
        public string ConfigurationName { get; set; }
        public string Description { get; set; }
    }
}
